def turn_right():
    turn_left()
    turn_left()
    turn_left()
def make_square():
    turn_left()
    move() 
    turn_right()
    move()    
    turn_right()
    move()
    turn_right()
    move()
def jump_hurdle():
    move()
    turn_left()
    move()
    turn_right()
    move()
    turn_right()
    move()
    turn_left()
    move()
    turn_left()
    
def cross_unit(): 
    jump_hurdle()
    move()
    turn_right()
    move()
    turn_right() 
    jump_hurdle()
    move()
    turn_right()
    move()
    
cross_unit()